#logging:
#  level:
#    org.springframework.boot.env: DEBUG
#    org.springframework.boot.context.config: DEBUG
#    org.springframework.cloud.kubernetes: DEBUG


# 设置监控
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m

# 开启spring doc
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

captcha:
  sms:
    # 危险，请勿泄露
    sign-name: Flyingjack小站
    template-code: SMS_465985630
  verify:
    strict: true # 是否需要验证ip

aliyun:
  sms:
    access:
      # 危险，请勿泄露
      id: ${SMS_ACCESS_ID}
      secret: ${SMS_ACCESS_SECRET}

spring:
  data:
    redis:
      host: beta.flyingcloud.com
      port: 6379
      password: ${REDIS_PASSWORD} # 通过k8s secret注入
      database: 0
      timeout: 5000 #5s
  mail:
    host: smtp.163.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-from: ${EMAIL_USERNAME}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true