apiVersion: v1
kind: ConfigMap
metadata:
  name: third-party-service-config
data:
  SPRING_PROFILES_ACTIVE: "default"
  application.yml: |
    server:
      port: 8080
      forward-headers-strategy: framework # 确保转发代理库头
    spring:
      application:
        name: third-party-service
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
          write-dates-as-timestamps: false
        time-zone: UTC
      messages:
        basename: i18n/message
        encoding: utf-8

    # 默认关闭spring doc
    springdoc:
      swagger-ui:
        enabled: false
      api-docs:
        enabled: false
        
    captcha:
      verify:
        strict: true # 是否需要验证ip