apiVersion: v1
kind: ServiceAccount
metadata:
  name: third-party-service-account

# 为sa赋予configmap读取权限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configs-read-role
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [get, watch, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-config-binding
subjects:
  - kind: ServiceAccount
    name: third-party-service-account
roleRef:
  kind: Role
  name: configs-read-role
  apiGroup: rbac.authorization.k8s.io

# 为sa赋予密码读取权限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-read-role
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets"]
    verbs: [get, watch, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secret-binding
subjects:
  - kind: ServiceAccount
    name: third-party-service-account
roleRef:
  kind: Role
  name: secrets-read-role
  apiGroup: rbac.authorization.k8s.io